IPv6 support (hopefully with fewer future transition pains)
git-svn-id: file:///home/klmitch/undernet-ircu/undernet-ircu-svn/ircu2/trunk@1094 c9e4aea6-c8fd-4c43-8297-357d70d61c8c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -862,6 +862,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-leak-detect          Turn on the leak detector(requires patched boehm)
+  --without-ipv6          disable IPv6 support (default is autodetect)
   --with-symlink=name     Name to give the symlink; if name is "no," no
                           symlink will be created.
   --with-mode=mode        Permissions (in octal) to give the binary
@@ -6713,6 +6714,69 @@ _ACEOF
 
 fi
 
+echo "$as_me:$LINENO: checking for struct sockaddr_in6" >&5
+echo $ECHO_N "checking for struct sockaddr_in6... $ECHO_C" >&6
+if test "${ac_cv_type_struct_sockaddr_in6+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/types.h>
+#include <netinet/in.h>
+
+int
+main ()
+{
+if ((struct sockaddr_in6 *) 0)
+  return 0;
+if (sizeof (struct sockaddr_in6))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_type_struct_sockaddr_in6=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_type_struct_sockaddr_in6=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_type_struct_sockaddr_in6" >&5
+echo "${ECHO_T}$ac_cv_type_struct_sockaddr_in6" >&6
+if test $ac_cv_type_struct_sockaddr_in6 = yes; then
+  unet_have_sockaddr_in6="yes"
+else
+  unet_have_sockaddr_in6="no"
+fi
+
 
 
 
@@ -8189,6 +8253,31 @@ if test x"$unet_cv_with_leak_detect" != xno; then
     if test x"$unet_cv_with_leak_detect" != xyes; then
        LIBS="-L$unet_cv_with_leak_detect $LIBS"
     fi
+fi
+
+
+# Check whether --with-ipv6 or --without-ipv6 was given.
+if test "${with_ipv6+set}" = set; then
+  withval="$with_ipv6"
+  ac_cv_use_ipv6=$withval
+else
+  ac_cv_use_ipv6=$unet_have_sockaddr_in6
+fi;
+echo "$as_me:$LINENO: checking whether to use IPv6" >&5
+echo $ECHO_N "checking whether to use IPv6... $ECHO_C" >&6
+if test "${ac_cv_use_ipv6+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_use_ipv6=no
+fi
+echo "$as_me:$LINENO: result: $ac_cv_use_ipv6" >&5
+echo "${ECHO_T}$ac_cv_use_ipv6" >&6
+if test x"$ac_cv_use_ipv6" != "xno" ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define IPV6
+_ACEOF
+
 fi
 
 echo "$as_me:$LINENO: checking whether to enable asserts" >&5
